const SUBMITTER_RESOURCE_ROLE_ID = 1
const PROJECT_USER_AUDIT_CREATE_TYPE = 1
const DESIGN_PROJECT_TYPE = 1
const DEVELOPMENT_PROJECT_TYPE = 2
const PROJECT_USER_AUDIT_DELETE_TYPE = 2
const COMPONENT_TESTING_PROJECT_TYPE = 5
const APPEALS_COMPLETE_EARLY_PROPERTY_ID = 13
const TIMELINE_NOTIFICATION_ID = 1
const COPILOT_POSTING_PROJECT_TYPE = 29
const NO_VALUE = 'NO'
const RESOURCE_ROLE_OBSERVER_ID = 12

module.exports = {
  SUBMITTER_RESOURCE_ROLE_ID,
  PROJECT_USER_AUDIT_CREATE_TYPE,
  DESIGN_PROJECT_TYPE,
  DEVELOPMENT_PROJECT_TYPE,
  PROJECT_USER_AUDIT_DELETE_TYPE,
  COMPONENT_TESTING_PROJECT_TYPE,
  APPEALS_COMPLETE_EARLY_PROPERTY_ID,
  TIMELINE_NOTIFICATION_ID,
  COPILOT_POSTING_PROJECT_TYPE,
  RESOURCE_ROLE_OBSERVER_ID,
  NO_VALUE
}
